### ISSUE TITLE
GHC: `make install` fails with "undefined method `mach_o_executable?'" on RHEL HPC

### ISSUE THREAD

**Issue by ebzheng** [Linuxbrew/homebrew-core#5170]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with `brew install`ing one, specific formula and not every time you run `brew`? If it's a general `brew` problem please file this issue at https://github.com/Linuxbrew/brew/issues/new.
- [x] If you have a macOS system and can replicate the problem on macOS with Homebrew, please report the issue to [Homebrew/core](https://github.com/Homebrew/homebrew-core) and follow their issue template from your macOS system. If you are unsure, please report the issue to Linuxbrew.
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] If `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

# Summary
In trying to install GHC (as a dependency of git-annex) on a RHEL HPC resource (hence, no sudo availability), the install errors out with the following: 

`undefined method 'mach_o_executable?' for #<Pathname:ghc/stage2/build/tmp/ghc-stage2>`

Inspecting the source for `ghc.rb` isn't particularly illuminating for me, unfortunately.

## Full console output
```
[ezheng@login01 ~]$ brew install git-annex
==> Installing dependencies for git-annex: ghc, cabal-install, gsasl, libmagic, lua@5.1, libquvi, quvi, cairo, py2cairo, bison, help2man, flex, gobject-introspection, pygobject3, libtiff, shared-mime-info, gdk-pixbuf, atk, graphite2, icu4c, harfbuzz, pango, hicolor-icon-theme, gtk+, pygobject, pygtk, xdot
==> Installing git-annex dependency: ghc
==> Downloading https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-src.tar.xz
Already downloaded: /ru-auth/local/home/ezheng/.cache/Homebrew/ghc-8.2.2.tar.xz
==> Downloading https://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz
Already downloaded: /ru-auth/local/home/ezheng/.cache/Homebrew/ghc--gmp-6.1.2.tar.xz
==> ./configure --prefix=/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Cellar/ghc/8.2.2/libexec/integer-gmp --with-pic --disable-shared
==> make
==> make check
==> make install
==> Downloading https://downloads.haskell.org/~ghc/8.2.2/ghc-8.2.2-x86_64-deb8-linux.tar.xz
Already downloaded: /ru-auth/local/home/ezheng/.cache/Homebrew/ghc--binary-8.2.2.tar.xz
Error: undefined method `mach_o_executable?' for #<Pathname:ghc/stage2/build/tmp/ghc-stage2>
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:153:in `block (2 levels) in install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:151:in `each'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:151:in `block in install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/ghc.rb:146:in `install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/build.rb:156:in `block (2 levels) in install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1093:in `block in brew'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1899:in `block (2 levels) in stage'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:557:in `with_env'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1898:in `block in stage'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:97:in `block in unpack'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:93:in `unpack'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:85:in `stage'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1876:in `stage'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1088:in `brew'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/build.rb:127:in `block in install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:557:in `with_env'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/build.rb:124:in `install'
/rugpfs/fs0/zhao_lab/store/ezheng/.linuxbrew/Homebrew/Library/Homebrew/build.rb:205:in `<main>'
```
## Brew doctor output
I don't believe there's anything relevant here, but I've attached it [here](https://gist.github.com/ebzheng/66105bd4a6a5d585515468abbf9bce42) for completeness.
The detected items are config scripts from a conda install for python 3 and an old version of git provided by the system (I'm not sure why brew isn't picking up the brewed version of git, but I don't think this is related).

## Brew gist-logs ghc output
Gist logs are available [here](https://gist.github.com/anonymous/14aa336143208b6edb1fcb605a917d16).

Thanks all for your help.

**Comment by iMichka** [comment]
There is a pull request open for that: #5260

**Comment by iMichka** [comment]
Fixed by #5260

**Comment by ebzheng** [comment]
Thanks for the work!

Weirdly, I still encounter problems, but I haven't yet been able to do enough troubleshooting to justify either reopening or starting a new issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iMichka** [comment]
Please open a new issue for that when you have done more troubleshooting. Thanks
