### ISSUE TITLE
ghc: ghc-pwd: cannot execute binary file

### ISSUE THREAD

**Issue by eyzhao** [Linuxbrew/homebrew-core#851]
I believe this issue has been reported before, and not sure a fix was ever found. Trying to install pandoc, and running into a issue installing ghc dependency.

Gist log: https://gist.github.com/758bc52f06d2368ce03f10cdfa2377ff

```
[ezhao@gphost01 ~]$ brew install ghc
==> Downloading https://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-src.tar.xz
Already downloaded: /home/ezhao/.cache/Homebrew/ghc-8.0.1.tar.xz
==> Downloading https://ftpmirror.gnu.org/gmp/gmp-6.1.0.tar.bz2
Already downloaded: /home/ezhao/.cache/Homebrew/ghc--gmp-6.1.0.tar.bz2
==> ./configure --prefix=/home/ezhao/.linuxbrew/Cellar/ghc/8.0.1/libexec/integer-gmp --with-pic --disable-shared
==> make
==> make check
==> make install
==> Downloading https://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-x86_64-apple-darwin.tar.xz
Already downloaded: /home/ezhao/.cache/Homebrew/ghc--binary-8.0.1.tar.xz
==> ./configure --prefix=/tmp/ghc-20160831-17727-16z1mpq/ghc-8.0.1/binary --with-gmp-includes=/home/ezhao/.linuxbrew/C
Last 15 lines from /home/ezhao/.cache/Homebrew/Logs/ghc/05.configure:
2016-08-31 15:59:17 -0700

./configure
--prefix=/tmp/ghc-20160831-17727-16z1mpq/ghc-8.0.1/binary
--with-gmp-includes=/home/ezhao/.linuxbrew/Cellar/ghc/8.0.1/libexec/integer-gmp/include
--with-gmp-libraries=/home/ezhao/.linuxbrew/Cellar/ghc/8.0.1/libexec/integer-gmp/lib
--with-ld=ld
--with-gcc=gcc

checking for path to top of build tree... utils/ghc-pwd/dist-install/build/tmp/ghc-pwd-bindist: line 3: /tmp/ghc--binary-20160831-17727-6uiwir/ghc-8.0.1/utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: cannot execute binary file
utils/ghc-pwd/dist-install/build/tmp/ghc-pwd-bindist: line 3: /tmp/ghc--binary-20160831-17727-6uiwir/ghc-8.0.1/utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: Success
configure: error: cannot determine current directory
```

**Comment by sjackman** [comment]
Sorry, I don't have a fix for this issue. 😖

**Comment by sjackman** [comment]
A workaround is to install GHC 7.10.3b like so:
```sh
brew install https://raw.githubusercontent.com/Linuxbrew/homebrew-core/6e4d8edba1f5d3a1aa796559d9bc3d7bdf1024cd/Formula/ghc.rb
```

**Comment by aaronwolen** [comment]
Thanks, I was able to install your workaround without issue. Is there a way to then tell cabal-install/pandoc to use GHC 7.10 and prevent them from trying to install GHC8?

**Comment by sjackman** [comment]
Unfortunately, no. If there's no fix in sight for `ghc` 8, we could add a `ghc@7` versioned formula so that `brew install ghc@7` would be the workaround.

**Comment by sjackman** [comment]
Fixed by #512.

**Comment by CristianCantoro** [comment]
Hi,

I don't know if I should open a new ticket or re-open this one, but I still encounter an error during the installation of `ghc` (as a dependency for `shellcheck`):
```bash
$ brew install ghc  
==> Downloading https://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-src.tar.xz
Already downloaded: /home/cconsonni/.cache/Homebrew/ghc-8.0.1.tar.xz
==> Downloading https://ftpmirror.gnu.org/gmp/gmp-6.1.1.tar.xz
Already downloaded: /home/cconsonni/.cache/Homebrew/ghc--gmp-6.1.1.tar.xz
==> ./configure --prefix=/home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/libexec/integer-gmp --with-pic --disable-shared
==> make
==> make check
==> make install
==> Downloading http://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-x86_64-deb8-linux.tar.xz
######################################################################## 100,0%
==> ./configure --prefix=/tmp/ghc-20161209-14520-1in7mpz/ghc-8.0.1/binary --with-gmp-includes=/home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/libexec/integer-gmp
==> make install
==> ./configure --prefix=/home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3 --with-gmp-includes=/home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/libexec/integer-gmp/in
==> make
==> make install
==> /home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/bin/ghc-pkg recache
Last 15 lines from /home/cconsonni/.cache/Homebrew/Logs/ghc/post_install.01.ghc-pkg:
2016-12-09 07:43:12 +0100

/home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/bin/ghc-pkg
recache

/home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/lib/ghc-8.0.1/bin/ghc-pkg: error while loading shared libraries: libncursesw.so.6: cannot open shared object file
: No such file or directory
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall ghc`
==> Summary
🍺  /home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3: 5,859 files, 1.1G, built in 301 minutes 52 seconds
```
and the executing `postinstall`:
```bash
$ brew postinstall ghc
==> /home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/bin/ghc-pkg recache
Last 15 lines from /home/cconsonni/.cache/Homebrew/Logs/ghc/post_install.01.ghc-pkg:
2016-12-11 17:26:15 +0100

/home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/bin/ghc-pkg
recache

/home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/lib/ghc-8.0.1/bin/ghc-pkg: error while loading shared libraries: libncursesw.so.6: cannot open shared object file
: No such file or directory

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
```

[Logs](https://gist.github.com/anonymous/7a8c48a4ee7cd0e33fab24c0110509f4) obtained with `brew gist-logs ghc`.

**Comment by sjackman** [comment]
> `ghc-pkg: error while loading shared libraries: libncursesw.so.6`

Could you please report the output of

```sh
which -a file
file /home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/lib/ghc-8.0.1/bin/ghc-pkg
ldd /home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/lib/ghc-8.0.1/bin/ghc-pkg
patchelf --print-interpreter --print-rpath --print-needed /home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/lib/ghc-8.0.1/bin/ghc-pkg
brew linkage ghc
```

**Comment by CristianCantoro** [comment]
Here they are:

```bash
$ which -a file
/usr/bin/file
```

```bash
$ file /home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/lib/ghc-8.0.1/bin/ghc-pkg
/home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/lib/ghc-8.0.1/bin/ghc-pkg:
ELF 64-bit LSB  executable,
x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24,
BuildID[sha1]=abb26fb0cb0fb9fbc736890bc882752dfea6df71, not stripped
```

`$ ldd /home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/lib/ghc-8.0.1/bin/ghc-pkg` -> [output](http://pastebin.com/raw/GLWcNPDY)

```bash
$ patchelf --print-interpreter --print-rpath --print-needed /home/cconsonni/.linuxbrew/Cellar/ghc/8.0.1_3/lib/ghc-8.0.1/bin/ghc-pkg
/lib64/ld-linux-x86-64.so.2
$ORIGIN/../terminfo-0.4.0.2:$ORIGIN/../ghc-boot-8.0.1:$ORIGIN/../ghc-boot-th-8.0.1:$ORIGIN/../Cabal-1.24.0.0:$ORIGIN/../process-1.4.2.0:$ORIGIN/../pretty-1.1.3.3:$ORIGIN/../directory-1.2.6.2:$ORIGIN/../unix-2.7.2.0:$ORIGIN/../time-1.6.0.1:$ORIGIN/../filepath-1.4.1.0:$ORIGIN/../binary-0.8.3.0:$ORIGIN/../containers-0.5.7.1:$ORIGIN/../bytestring-0.10.8.1:$ORIGIN/../deepseq-1.4.2.0:$ORIGIN/../array-0.5.1.1:$ORIGIN/../base-4.9.0.0:$ORIGIN/../integer-gmp-1.0.0.1:$ORIGIN/../ghc-prim-0.5.0.0:$ORIGIN/../rts
libncursesw.so.6
librt.so.1
libutil.so.1
libdl.so.2
libpthread.so.0
libm.so.6
libHSterminfo-0.4.0.2-ghc8.0.1.so
libHSghc-boot-8.0.1-ghc8.0.1.so
libHSghc-boot-th-8.0.1-ghc8.0.1.so
libHSCabal-1.24.0.0-ghc8.0.1.so
libHSprocess-1.4.2.0-ghc8.0.1.so
libHSpretty-1.1.3.3-ghc8.0.1.so
libHSdirectory-1.2.6.2-ghc8.0.1.so
libHSunix-2.7.2.0-ghc8.0.1.so
libHStime-1.6.0.1-ghc8.0.1.so
libHSfilepath-1.4.1.0-ghc8.0.1.so
libHSbinary-0.8.3.0-ghc8.0.1.so
libHScontainers-0.5.7.1-ghc8.0.1.so
libHSbytestring-0.10.8.1-ghc8.0.1.so
libHSdeepseq-1.4.2.0-ghc8.0.1.so
libHSarray-0.5.1.1-ghc8.0.1.so
libHSbase-4.9.0.0-ghc8.0.1.so
libHSinteger-gmp-1.0.0.1-ghc8.0.1.so
libHSghc-prim-0.5.0.0-ghc8.0.1.so
libHSrts-ghc8.0.1.so
libffi.so.6
libc.so.6
```

`brew linkage ghc` -> [output](http://pastebin.com/raw/A40UJaEn)

**Comment by sjackman** [comment]
`/home/cconsonni/.linuxbrew/lib` is missing from the RPATH. I'm not sure why. As a workaround, try
```sh
brew patchelf ghc
```

**Comment by sjackman** [comment]
Just to confirm, the file `libncursesw.so.6` exists in `/home/cconsonni/.linuxbrew/lib`?
```sh
ls -l /home/cconsonni/.linuxbrew/lib/libncursesw.so.6
```

**Comment by CristianCantoro** [comment]
When executing
```bash
brew patchelf ghc
```
I get this error:
```bash
$ brew patchelf ghc
==> Fixing up ghc...
Error: wrong number of arguments (4 for 1)
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/cconsonni/.linuxbrew/Library/Homebrew/extend/os/linux/keg_relocate.rb:2:in `relocate_dynamic_linkage'
/home/cconsonni/.linuxbrew/Library/Homebrew/cmd/patchelf.rb:24:in `block in patchelf_formula'
/home/cconsonni/.linuxbrew/Library/Homebrew/keg.rb:292:in `block in lock'
/home/cconsonni/.linuxbrew/Library/Homebrew/formula_lock.rb:25:in `with_lock'
/home/cconsonni/.linuxbrew/Library/Homebrew/keg.rb:288:in `lock'
/home/cconsonni/.linuxbrew/Library/Homebrew/cmd/patchelf.rb:23:in `patchelf_formula'
/home/cconsonni/.linuxbrew/Library/Homebrew/compat/global.rb:7:in `call'
/home/cconsonni/.linuxbrew/Library/Homebrew/compat/global.rb:7:in `method_missing'
/home/cconsonni/.linuxbrew/Library/Homebrew/cmd/patchelf.rb:31:in `block in patchelf_formulae'
/home/cconsonni/.linuxbrew/Library/Homebrew/cmd/patchelf.rb:31:in `each'
/home/cconsonni/.linuxbrew/Library/Homebrew/cmd/patchelf.rb:31:in `patchelf_formulae'
/home/cconsonni/.linuxbrew/Library/Homebrew/compat/global.rb:7:in `call'
/home/cconsonni/.linuxbrew/Library/Homebrew/compat/global.rb:7:in `method_missing'
/home/cconsonni/.linuxbrew/Library/Homebrew/cmd/patchelf.rb:39:in `patchelf'
/home/cconsonni/.linuxbrew/Library/Homebrew/compat/global.rb:7:in `call'
/home/cconsonni/.linuxbrew/Library/Homebrew/compat/global.rb:7:in `method_missing'
/home/cconsonni/.linuxbrew/Library/Homebrew/brew.rb:94:in `<main>'
```

I confirm that `ibncursesw.so.6` exists in `/home/cconsonni/.linuxbrew/lib`:
```bash
$ ls -l /home/cconsonni/.linuxbrew/lib/libncursesw.so.6
lrwxrwxrwx 1 cconsonni dbtrento 44 dic 11 17:34 /home/cconsonni/.linuxbrew/lib/libncursesw.so.6 -> ../Cellar/ncurses/6.0_2/lib/libncursesw.so.6
```

**Comment by CristianCantoro** [comment]
Ok, I did a `brew update` (twice) and the again `brew patchelf ghc` and it worked this time.

**Comment by CristianCantoro** [comment]
It seems that now the issue with this package is resolved, still I have encountered another issue and reported a new bug. Thanks for your help.

**Comment by sjackman** [comment]
Glad to hear it.
